#!/usr/bin/env ruby
git_bundles     = File.read(File.expand_path("../bundles", __FILE__)).split("\n")

# slacks bundles...TODO rebundle...
#git_bundles = [
  #"git://github.com/altercation/vim-colors-solarized.git",
  #"git://github.com/kana/vim-textobj-user.git",
  #"git://github.com/kien/ctrlp.vim.git",
  #"git://github.com/mileszs/ack.vim.git",
  #"git://github.com/nelstrom/vim-textobj-rubyblock.git",
  #"git://github.com/scrooloose/nerdtree.git",
  #"git://github.com/slack/vim-align.git",
  #"git://github.com/jlanzarotta/bufexplorer.git",
  #"git://github.com/tpope/vim-bundler.git",
  #"git://github.com/tpope/vim-commentary.git",
  #"git://github.com/tpope/vim-fugitive.git",
  #"git://github.com/tpope/vim-markdown.git",
  #"git://github.com/tpope/vim-rails.git",
  #"git://github.com/tpope/vim-surround.git",
  #"git://github.com/vim-ruby/vim-ruby.git",
  #"git://github.com/vim-scripts/matchit.zip.git",
#]

vim_org_scripts = File.read(File.expand_path("../scripts", __FILE__)).split("\n").map(&:split)

require 'fileutils'
require 'open-uri'

bundle_dir = File.expand_path("../bundle", __FILE__)

puts bundle_dir

FileUtils.mkdir_p(bundle_dir)
FileUtils.cd(bundle_dir)

git_bundles.each do |url|
  dir = File.basename(url).gsub(/\.git$/, '')
  if File.exists?(dir)
    FileUtils.cd(dir)
    puts %x[git pull origin master]
    FileUtils.cd(bundle_dir)
  else
    puts %x[git clone #{url} #{dir}]
  end
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
